apiVersion: v1
kind: ConfigMap
metadata:
  name: laptop-metrics-grafana-datasource
  labels:
    app: laptop-metrics
data:
  influxdb.yml: |
    apiVersion: 1
    datasources:
    - name: influxdb
      type: influxdb
      access: proxy
      url: http://laptop-metrics-influxdb-internal:8086
      database: collectd
      editable: true
