kind: ConfigMap
apiVersion: v1
metadata:
  name: dirstats-script
  namespace: prometheus
data:
  update-dirstats.sh: |-
    #! /bin/bash
    set -e
    TARGET_FILE="/target/dirstats.prom"

    cd /source
    rm ${TARGET_FILE}

    for i in ./*; do
        echo "Gathering stats from ${i}..."
        du --block-size=1 --summarize $(basename $i) \
      | sed -ne 's/\\/\\\\/;s/"/\\"/g;s/^\([0-9]\+\)\t\(.*\)$/node_directory_size_bytes{directory="\2"} \1/p' >> ${TARGET_FILE}
    done

    echo "Stats generated: "
    cat ${TARGET_FILE}

