apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:  
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.0.6
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-data
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ORG_ROLE
          value: "Viewer"
        - name: GF_SERVER_ROOT_URL
          value: "http://grafana.kelog.pl"
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-admin-password
              key: password
      volumes:
      - name: grafana-data
        hostPath:
          path: /var/k8s-hostpath/grafana-data
      nodeSelector:
        ismasterhost: 'yes'
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus
spec:
  selector:
    app: grafana
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: prometheus
spec:
  rules:
  - host: prometheus.kelog.pl
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
  - host: grafana.kelog.pl
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 80
