kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'node'
        scrape_interval: 10s
        static_configs:
        - targets: ['kelog.pl:9100', '192.168.79.2:9100']
      - job_name: 'kubernetes'
        scrape_interval: 10s
        static_configs:
        - targets: ['prometheus-kubernetes-web:4567']
      - job_name: 'blackbox'
        metrics_path: /probe
        params:
          module: [icmp]
        static_configs:
        - targets:
          - 192.168.1.25
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 192.168.123.2:9115  # This is your blackbox exporter.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: prometheus
  labels:
    app: prometheus
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.13.0
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: data
          mountPath: /prometheus
        ports:
        - containerPort: 9090
      volumes:
      - name: config
        configMap:
         name: prometheus-config
      - name: data
        hostPath:
          path: /var/k8s-hostpath/prometheus-data 

---
kind: Service
apiVersion: v1
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
