- name: Install ffmpeg as a dependency for yt-dlp conversion features
  apt:
    pkg: ffmpeg
    state: present

- name: Download yt-dlp executable
  get_url:
    url: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
    dest: /usr/local/bin
    mode: '775'

- name: Force update of yt-dlp
  shell: /usr/local/bin/yt-dlp -U
  register: out

- name: Print update status of yt-dlp
  debug:
    var: out.stdout_lines

- name: Put MP3 download script
  template:
    src: ../files/yt-dlp-mp3.sh
    dest: /home/kelog/bin/yt-dlp-mp3.sh
    mode: '755'
