- name: Configure tools on laptop only
  block:
  - name: Install node-exporter
    apt:
      name: prometheus-node-exporter
      state: present
  - name: Enable node-exporter
    systemd:
      name: prometheus-node-exporter
      enabled: true
  - name: Copy Windows reboot script and WiFi reset script
    copy:
      src: "{{ role_path }}/files/{{ item }}.sh"
      dest: "/usr/local/bin/{{ item }}"
      owner: root
      group: root
      mode: '0770'
    with_items:
    - windows-reboot
    - wifi-reset
  - name: Allow kelog to run windows-reboot as root
    blockinfile:
      path: /etc/sudoers
      block: |
        kelog galera = (root) NOPASSWD: /usr/local/bin/windows-reboot
  when: inventory_hostname == 'dell'

- name: Check if kubectx is already installed
  stat:
    path: /opt/kubectx
  register: check_kubectx

- name: Install kubectx and kubens
  block:
  - name: Clone kubectx repository
    git:
      repo: https://github.com/ahmetb/kubectx
      dest: /opt/kubectx
      version: master
  - name: Symlink kubectx and kubens executables
    file:
      src: "/opt/kubectx/{{ item }}"
      dest: "/usr/local/bin/{{ item }}"
      state: link
    with_items:
    - kubectx
    - kubens
  when: not check_kubectx.stat.exists


- name: Check if k9s is already installed
  stat:
    path: /usr/local/bin/k9s
  register: check_k9s

- name: Install k9s
  block:
  - name: Clear old k9s downloaded archive
    file:
      path: /tmp/k9s.tar.gz
      state: absent
  - name: Fetch k9s binary in form of tar.gz archive
    get_url:
      url: "{{ urls.k9s }}"
      dest: /tmp/k9s.tar.gz
  - name: Unpack k9s binary
    unarchive:
      src: /tmp/k9s.tar.gz
      remote_src: yes
      dest: /usr/local/bin
  when: not check_k9s.stat.exists

- name: Check if fzf is already installed
  stat:
    path: /usr/local/bin/fzf
  register: check_fzf

- name: Install fzf
  block:
  - name: Download fzf from GitHub
    get_url:
      url: "{{ urls.fzf }}"
      dest: /tmp/fzf.tar.gz
  - name: Unpack fzf
    unarchive:
      src: /tmp/fzf.tar.gz
      dest: /usr/local/bin/
      remote_src: yes
  when: not check_fzf.stat.exists


- name: Install ripgrep
  apt:
    pkg: ripgrep
    state: present

- name: Install yt-dlp with dependencies and extra scripts
  block:
  - name: Install ffmpeg as a dependency for yt-dlp conversion features
    apt:
      pkg: ffmpeg
      state: present
  - name: Check if yt-dlp is already installed
    stat:
      path: /usr/local/bin/yt-dlp
    register: yt_dlp_check
  - name: Download yt-dlp executable
    get_url:
      url: "{{ urls.yt_dlp }}"
      dest: /usr/local/bin
      mode: '775'
    when: not yt_dlp_check.stat.exists
  - name: Force update of yt-dlp
    shell: /usr/local/bin/yt-dlp -U
    register: stdout
    when: yt_dlp_check.stat.exists
  - name: Print update status of yt-dlp
    debug:
      var: stdout.stdout_lines
  - name: Put yt-dlp video download script
    template:
      src: ../files/yy.sh
      dest: /home/kelog/bin/yy.sh
      mode: '755'
  - name: Put yt-dlp audio download script
    vars:
      yt_dlp_extra_args: "-x --audio-format=mp3"
    template:
      src: ../files/yy.sh
      dest: /home/kelog/bin/yymp3.sh
      mode: '755'
