version: '3.1'
services:
  frontend:
    image: kelog/chat:frontend-latest
    environment:
      - BACKEND_URL=http://chat.kelog.pl
    ports:
      - 51726:80
      
  backend:
    image: kelog/chat:backend-latest
    ports:
        - 51727:8080
