version: '3.1'
services:
  facerec:
    image: kelog/facerec:latest
    ports:
      - 61934:8080
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
