version: '3.1'
services:
  frontend:
    image: kelog/jazzstandards:frontend-latest
    ports:
      - 51977:80
    deploy:
      resources:
        limits:
          memory: 20M
        reservations:
          memory: 20M
      
  backend:
    image: kelog/jazzstandards:backend-latest
    ports:
      - 52190:8080
    deploy:
      resources:
        limits:
          memory: 200M
        reservations:
          memory: 200M
      
  mysql:
    image: mariadb
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jazzstandards
    deploy:
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
      
volumes:
  data:
