version: '3.1'
services:
  frontend:
    image: kelog/jazzstandards:frontend-latest
    ports:
      - 51977:80
      
  backend:
    image: kelog/jazzstandards:backend-latest
    ports:
      - 52190:8080
      
  mysql:
    image: mariadb
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jazzstandards
      
volumes:
  data:
