apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: efk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - name: fluentd
        image: k8s.gcr.io/fluentd-elasticsearch:v2.4.0
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: libsystemddir
          mountPath: /host/lib
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      # It is needed to copy systemd library to decompress journals
      - name: libsystemddir
        hostPath:
          path: /usr/lib64
      - name: config-volume
        configMap:
          name: fluentd-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: efk
data:
  containers.input.conf: |-
    <source>
      type tail
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/*fluentd*"]
      pos_file /var/log/es-containers.log.pos

      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      read_from_head true
      format json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>

    <match **>
       type elasticsearch
       log_level info
       include_tag_key true
       host elasticsearch
       port 9200
       logstash_format true

       # https://github.com/uken/fluent-plugin-elasticsearch/issues/306
       reload_connections false

       # Set the chunk limits.
       buffer_chunk_limit 1M
       buffer_queue_limit 7
       flush_interval 4s
       # Never wait longer than 4 minutes between retries.
       max_retry_wait 29
       # Disable the limit on the number of retries (retry forever).
       disable_retry_limit
       # Use multiple threads for processing.
       num_threads 1
    </match>
