---

- name: Install Kubernetes prereqs
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https 
    - curl

- name: Add Kubernetes APT repository key
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

- name: Put Kubernetes repository information
  template:
    src: kubernetes.list
    dest: /etc/apt/sources.list.d/kubernetes.list

- name: Install Kubernetes and required stuff
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - docker.io
    - haveged
    - iftop
    
- name: Disable systemd-resolved
  systemd:
    name: systemd-resolved
    enabled: no
    state: stopped
    
- name: Write static resolv.conf
  template:
    src: resolv.conf
    dest: /etc/resolv.conf

- name: Create folders for Docker volumes
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0777
  with_items:
    - '/var/kelog.pl/k8s-jazzstandards'
    - '/var/kelog.pl/k8s-temperature'

- name: Print help
  debug:
    msg:
    - '> kubeadm init --apiserver-advertise-address={{ ansible_default_ipv4.address }} --pod-network-cidr=10.244.0.0/16'
    - '> kubectl taint nodes --all node-role.kubernetes.io/master-'
    - '> kubectl label nodes NODENAME isstoragehost=yes

