version: '2'
services:
  collector:
    image: kelog/temperature:raspberry
    environment:
      BACKEND_TYPE: mysql
      MYSQL_HOST: kelog.pl
      MYSQL_PORT: 31306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: temperature
      INTERVAL: 60
      PLACE: raspberry
    restart: always
