apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: es-cleanup
  namespace: efk
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: cleanup-job
            image: python:3.8.0a3-stretch
            args:
            - python3
            - /cleanup-script/cleanup.py
            env:
            - name: ES_HOST_PORT
              value: 'elasticsearch:9200'
            - name: KEEP_LAST_COUNT
              value: '14'
            volumeMounts:
            - name: cleanup-script
              mountPath: /cleanup-script
          volumes:
          - name: cleanup-script
            configMap:
              name: cleanup-script
