---
- name: Download node_exporter binary
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v0.17.0/node_exporter-0.17.0.linux-{{ node_exporter_cpu_arch }}.tar.gz"
    dest: /tmp/node_exporter.tar.gz
    
- name: Extract node_exporter archive
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /tmp
    remote_src: yes
    
- name: Copy node_exporter binary
  copy:
    src: "/tmp/node_exporter-0.17.0.linux-{{ node_exporter_cpu_arch }}/node_exporter"
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    group: root
    mode: 0755
    
- name: Copy systemd unit configuration
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    
- name: Enable node_exporter service
  systemd:
    name: node_exporter
    enabled: yes
    state: restarted
