apiVersion: v1
kind: ConfigMap
metadata:
  name: five9s-config
  labels:
    app: five9s
data:
  config.yml: |
    ---
    name: aleksandergrzybowski.pl
    description: aleksandergrzybowski.pl
    check:
      type: http
      url: 'https://aleksandergrzybowski.pl'
    ---
    name: chat.kelog.pl-frontend
    description: Chat (frontend)
    check:
      type: http
      url: 'http://chat.kelog.pl/'
    ---
    name: chat.kelog.pl-backend
    description: Chat (backend)
    check:
      type: http
      url: 'http://chat.kelog.pl/health'
    ---
    name: temperature.kelog.pl-grafana
    description: Temperature (Grafana)
    check:
      type: http
      url: 'http://temperature.kelog.pl/api/health'
    ---
    name: temperature.kelog.pl-backend
    description: Temperature (backend)
    check:
      type: http
      url: 'http://temperature.kelog.pl/actuator/health'
    ---
    name: jazzstandards.kelog.pl-frontend
    description: Jazzstandards (frontend)
    check:
      type: http
      url: 'http://jazzstandards.kelog.pl'
    ---
    name: jazzstandards.kelog.pl-backend
    description: Jazzstandards (backend)
    check:
      type: http
      url: 'http://jazzstandards.kelog.pl/api/songs'
    ---
    name: smsalerts.kelog.pl
    description: SmsAlerts
    check:
      type: http
      url: 'http://smsalerts.kelog.pl'
    ---
    name: facerec.kelog.pl
    description: Facerec
    check:
      type: http
      url: 'https://facerec.kelog.pl'
    ---
    name: 2048.kelog.pl
    description: 2048 (Info site)
    check:
      type: http
      url: 'http://2048.kelog.pl'
    ---
    name: heapster.kelog.pl
    description: Heapster
    check:
      type: http
      url: 'http://heapster.kelog.pl'
    ---
    name: ovh-diskspace
    description: kelog.pl disk
    check:
      type: ssh
      host: kelog.pl
      keyPath: /run/secrets/KELOGPL_ID_RSA
      user: icinga
      command: check_disk.sh
    ---
    name: ovh-cpu
    description: kelog.pl CPU
    check:
      type: ssh
      host: kelog.pl
      keyPath: /run/secrets/KELOGPL_ID_RSA
      user: icinga
      command: check_load.sh
