version: '3.3'
services:
  mysql:
    image: mariadb:latest
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: temperature
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
      
  grafana:
    image: kelog/temperature:grafana
    ports:
      - 52222:3000
    environment:
      GF_DASHBOARDS_JSON_ENABLED: 'true'
      GF_DASHBOARDS_JSON_PATH: /dashboards
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
    deploy:
      resources: 
        limits:
          memory: 50M
        reservations:
          memory: 50M

  backend:
    image: kelog/temperature:backend
    ports:
      - 51111:8080
    environment:
      SPRING_PROFILES_ACTIVE: production 
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/temperature
      SPRING_DATASOURCE_USERNAME: root    
      SPRING_DATASOURCE_PASSWORD: root
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
  
volumes:
  data:
