version: '3.3'
services:
  mysql:
    image: mariadb:latest
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: tempdata
      MYSQL_ROOT_PASSWORD: root
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 150M
        reservations:
          memory: 150M
      
  grafana:
    image: grafana/grafana:5.0.0
    ports:
      - 52222:3000
    configs:
      - source: grafana-mysql.yml
        target: /etc/grafana/provisioning/datasources/datasource.yml
    deploy:
      resources: 
        limits:
          memory: 50M
        reservations:
          memory: 50M

  backend:
    image: kelog/temperature:backend
    ports:
      - 51111:8080
    environment:
      SPRING_PROFILES_ACTIVE: production 
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
  

configs:
  grafana-mysql.yml:
    external: true
