apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: heapster
data:
  influxdb.yml: |
    apiVersion: 1
    datasources:
    - name: heapster-influx
      type: influxdb
      access: proxy
      url: http://influxdb:8086
      database: k8s
      editable: true
