apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: heapster
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: heapster
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: k8s.gcr.io/heapster-amd64:v1.5.3
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://influxdb.heapster.svc:8086
---
apiVersion: v1
kind: Service
metadata:
  name: heapster
  namespace: heapster
spec:
  selector:
    app: heapster
  ports:
  - port: 80
    targetPort: 8082
