version: '3.3'

services:
  influx:
    image: influxdb
    volumes:
      - influx_data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: cadvisor
    deploy:
      replicas: 1

  grafana:
    image: grafana/grafana:master
    ports:
      - "8002:3000"
    environment:
      GF_DASHBOARDS_JSON_ENABLED: 'true'
      GF_DASHBOARDS_JSON_PATH: /dashboards
    configs:
      - source: dashboard.json
        target: /dashboards/dashboard.json
        mode: 0777
        uid: '104'
        gid: '107'
      - source: dashboards.yml
        target: /etc/grafana/provisioning/dashboards/dashboards.yml
        mode: 0777
        uid: '104'
        gid: '107'
      - source: influx.yml
        target: /etc/grafana/provisioning/datasources/influx.yml
        mode: 0777
        uid: '104'
        gid: '107'
    deploy:
      replicas: 1

  cadvisor:
    image: google/cadvisor
    hostname: '{{.Node.Hostname}}'
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global


configs:
  dashboard.json:
    external: true
  dashboards.yml:
    external: true
  influx.yml:
    external: true

volumes:
  influx_data:
