- name: Install WireGuard
  apt:
    name: wireguard
    state: present
    
- name: Extract public keys
  shell: |
    cat {{ playbook_dir }}/secrets/wireguard-private-remote.b64 | wg pubkey > {{ playbook_dir }}/secrets/wireguard-public-remote.b64
    cat {{ playbook_dir }}/secrets/wireguard-private-local.b64 | wg pubkey > {{ playbook_dir }}/secrets/wireguard-public-local.b64
  when: inventory_hostname == 'dell'

- name: Load keys as variables
  set_fact:
    wireguard_private_remote: "{{ lookup('file', playbook_dir + '/secrets/wireguard-private-remote.b64') }}"
    wireguard_public_remote:  "{{ lookup('file', playbook_dir + '/secrets/wireguard-public-remote.b64') }}"
    wireguard_private_local: "{{ lookup('file', playbook_dir + '/secrets/wireguard-private-local.b64') }}"
    wireguard_public_local:  "{{ lookup('file', playbook_dir + '/secrets/wireguard-public-local.b64') }}"

- name: Put WireGuard config files
  template:
    src: "../files/wg0-{{ 'client' if (inventory_hostname == 'dell') else 'server' }}.conf"
    dest: /etc/wireguard/wg0.conf
    owner: root

- name: Enable WireGuard service
  systemd:
    name: wg-quick@wg0.service
    enabled: true
    state: restarted
