version: '3.1'
services:
  icinga:
    image: kelog/icinga2:latest
    ports:
      - 57270:80
    secrets:
      - KELOGPL_ID_RSA
    restart: always
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M

secrets:
  KELOGPL_ID_RSA:
    external: true


