version: '3.1'
services:
  icinga:
    image: kelog/icinga2:latest
    ports:
      - 57270:80
    secrets:
      - KELOGPL_ID_RSA
    environment:
      - ICINGAWEB2_ADMIN_USER=${ICINGAWEB2_ADMIN_USER}
      - ICINGAWEB2_ADMIN_PASS=${ICINGAWEB2_ADMIN_PASS}
    restart: always
    deploy:
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M

secrets:
  KELOGPL_ID_RSA:
    external: true


