version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      ES_JAVA_OPTS: '-Xms128m -Xmx128m'
      xpack.security.enabled: 'false'
      xpack.monitoring.enabled: 'false'
      xpack.graph.enabled: 'false'
      xpack.watcher.enabled: 'false'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M

  logstash:
    image: docker.elastic.co/logstash/logstash:5.3.2
    environment:
      XPACK_MONITORING_ENABLED: 'false'
    configs:
      - source: logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf
    deploy:
      resources:
        limits:
          memory: 400M
        reservations:
          memory: 400M

  logspout:
    image: bekt/logspout-logstash
    environment:
      ROUTE_URIS: 'logstash://logstash:5000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      resources:
        limits:
          memory: 20M
        reservations:
          memory: 20M

  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    ports:
      - 61555:5601
    environment:
      ELASTICSEARCH_URL: 'http://elasticsearch:9200'
      XPACK_SECURITY_ENABLED: 'false'
      XPACK_MONITORING_ENABLED: 'false'
      NODE_OPTIONS: '--max-old-space-size=600'
    deploy:
      resources:
        limits:
          memory: 900M
        reservations:
          memory: 900M

configs:
  logstash.conf:
    external: true

volumes:
  esdata:
