---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icinga
spec:
  selector:
    matchLabels:
      app: icinga
  replicas: 1
  template:
    metadata:
      labels:
        app: icinga
    spec:
      containers:
      - name: icinga
        image: kelog/icinga2:latest
        resources:
          limits:
            memory: "300Mi"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
        env:
        - name: ICINGAWEB2_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: icinga-creds
              key: username
        - name: ICINGAWEB2_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              name: icinga-creds
              key: password
        - name: ICINGA2_FEATURE_DIRECTOR
          value: 'false'
---
apiVersion: v1
kind: Service
metadata:
  name: icinga
spec:
  selector:
    app: icinga
  ports:
  - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: icinga
spec:
  rules:
  - host: icinga.kelog.pl
    http:
      paths:
      - path:
        backend:
          serviceName: icinga
          servicePort: 80


