- name: Create directory for containerd configuration file
  file:
    path: /etc/containerd
    state: directory
- name: Put containerd config for kubeadm with SystemdCgroup = true
  copy:
    src: "{{ role_path }}/files/config.toml"
    dest: /etc/containerd/config.toml
- name: Install containerd
  apt:
    pkg: containerd
    state: present

- name: Check if buildkit is already installed
  stat:
    path: /usr/local/bin/buildkitd
  register: check_buildkit
- name: Install buildkit
  shell: |
    cd /tmp
    rm -rf buildkit.tar.gz
    wget https://github.com/moby/buildkit/releases/download/v0.15.1/buildkit-v0.15.1.linux-amd64.tar.gz -O buildkit.tar.gz
    tar xf buildkit.tar.gz
    cp ./bin/* /usr/local/bin
  when: not check_buildkit.stat.exists
- name: Put systemd service for buildkit
  copy:
    src: "{{ role_path }}/files/buildkit.service"
    dest: /etc/systemd/system/buildkit.service
- name: Enable buildkit service
  systemd:
    name: buildkit.service
    state: started
    enabled: true
    daemon_reload: true

- name: Check if nerdctl is already installed
  stat:
    path: /usr/local/bin/nerdctl
  register: check_nerdctl
- name: Install nerdctl
  block:
  - name: Download nerdctl
    get_url:
      url: https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-1.7.6-linux-amd64.tar.gz
      dest: /tmp/nerdctl.tar.gz
  - name: Unpack nerdctl
    unarchive:
      remote_src: true
      src: /tmp/nerdctl.tar.gz
      dest: /usr/local/bin/
  when: not check_nerdctl.stat.exists

- name: Enable IP forwarding for Kubernetes
  copy:
    src: "{{ role_path }}/files/k8s.conf"
    dest: /etc/sysctl.d/k8s.conf
- name: Force reload of sysctl parameters
  shell: sysctl --system
- name: Add required module for flannel to work
  lineinfile:
    path: /etc/modules
    line: br_netfilter
    create: yes
    state: present
- name: Force required module load now without reboot
  shell: "modprobe br_netfilter"

- name: Install certbot for Lets Encrypt
  apt:
    pkg: certbot
    state: present

- name: Check if kelog.pl repository needs to be cloned
  stat:
    path: /home/kelog/kelog.pl
  register: check_kelog_pl
- name: Clone main infrastructure repository for later
  git:
    repo: 'https://github.com/AleksanderGrzybowski/kelog.pl.git'
    dest: /home/kelog/kelog.pl
    version: 'master' 
  when: not check_kelog_pl.stat.exists
    
