apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: baza-zespolsdg-backup
spec:
  schedule: "0 0 */2 * *"
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          serviceAccountName: baza-zespolsdg-sa
          restartPolicy: Never
          containers:
          - name: baza-zespolsdg-backup
            image: ubuntu:latest
            imagePullPolicy: Always
            args:
            - bash
            - /backup-script/backup.sh
            env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: baza-zespolsdg-secrets  
                  key: aws_access_key
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: baza-zespolsdg-secrets  
                  key: aws_secret_key
            volumeMounts:
            - name: backup-script
              mountPath: /backup-script
            - name: source-folder
              mountPath: /source
          volumes:
          - name: backup-script
            configMap:
              name: baza-zespolsdg-backup-script
          - name: source-folder
            hostPath:
              path: /var/k8s-hostpath/baza-zespolsdg-data


