apiVersion: v1
kind: ServiceAccount
metadata:
  name: baza-zespolsdg-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: baza-zespolsdg-crb
subjects:
  - kind: ServiceAccount
    name: baza-zespolsdg-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

