---

- hosts: all
  gather_facts: False
  become: yes
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    
- hosts: all
  become: yes
  roles:
    - role: openvpn

- hosts: raspberry
  become: yes
  roles:
    - role: raspberry-openvpn
