kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: efk
data:
  containers.input.conf: |-
    <source>
      type tail
      path /var/log/containers/*.log
      exclude_path ["/var/log/containers/*fluentd*"]
      pos_file /var/log/es-containers.log.pos

      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      read_from_head true
      format json
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%NZ
    </source>

    <match **>
       type elasticsearch
       log_level info
       include_tag_key true
       host elasticsearch
       port 9200
       logstash_format true

       # https://github.com/uken/fluent-plugin-elasticsearch/issues/307
       reload_connections false

       # Set the chunk limits.
       buffer_chunk_limit 2M
       buffer_queue_limit 8
       flush_interval 5s
       # Never wait longer than 5 minutes between retries.
       max_retry_wait 30
       # Disable the limit on the number of retries (retry forever).
       disable_retry_limit
       # Use multiple threads for processing.
       num_threads 2
    </match>
