---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aleksandergrzybowskipl
  namespace: default
spec:
  selector:
    matchLabels:
      app: aleksandergrzybowskipl
  replicas: 1
  template:
    metadata:
      labels:
        app: aleksandergrzybowskipl
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: aleksandergrzybowskipl
        imagePullPolicy: Always
        image: registry.kelog.pl/kelog/aleksandergrzybowski.pl:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          failureThreshold: 30

---
apiVersion: v1
kind: Service
metadata:
  name: aleksandergrzybowskipl
  namespace: default
spec:
  selector:
    app: aleksandergrzybowskipl
  ports:
  - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aleksandergrzybowski
  namespace: default
spec:
  tls:
  - hosts:
    - aleksandergrzybowski.pl
    secretName: aleksandergrzybowski.pl
  rules:
  - host: aleksandergrzybowski.pl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aleksandergrzybowskipl
            port:
              number: 80

