- name: Clone kubectx repository
  git:
    repo: https://github.com/ahmetb/kubectx 
    dest: /opt/kubectx
    version: master

- name: Symlink kubectx and kubens executables
  file:
    src: "/opt/kubectx/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  with_items:
  - kubectx
  - kubens
