#! /bin/bash

if [ "$1" = "light" ]; then
    echo "Enabling light mode"
    rm -f ~/.dark
    touch ~/.light
    cp ~/.config/k9s/skins/solarized-light.yml ~/.config/k9s/skin.yml
elif [ "$1" = "dark" ]; then
    echo "Enabling dark mode"
    rm -rf ~/.light
    touch ~/.dark
    rm -rf ~/.config/k9s/skin.yml
else
    echo "Usage: theme <dark/light>"
    exit 1
fi

tmux source-file ~/.tmux.conf
