set nocompatible " force Vim

" Vundle
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Bundle 'altercation/vim-colors-solarized'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'machakann/vim-highlightedyank'
Plugin 'tpope/vim-commentary'
Plugin 'raimondi/delimitmate'
Plugin 'hashivim/vim-terraform'


call vundle#end()

filetype plugin indent on

" 4-space tabs
set ts=4
set sw=4
set expandtab cursorline


" some view stuff
set showcmd
set number
set ruler
set laststatus=2

" colors
syntax on
if filereadable(expand('~/.light'))
    set background=light
else
    set background=dark
endif

set t_Co=16
colorscheme selenized

" some saner settings
set ignorecase
set wrap
set linebreak
set noswapfile
set incsearch

" mouse enabled
set mouse=a

" fix insane default behavior
noremap <buffer> <silent> k gk
noremap <buffer> <silent> j gj
noremap <buffer> <silent> 0 g0
noremap <buffer> <silent> $ g$

" use single clipboard
set clipboard=unnamed,unnamedplus

" things that should be default, but aren't
nnoremap ' `
nnoremap ` '
noremap Q :echo<CR>
set timeoutlen=1000 ttimeoutlen=0
set scrolloff=2

" leader key
let mapleader = ","
nmap <Leader>n :NERDTreeToggle<CR>
nmap <Leader>w :wa<CR>
nmap <Leader>x :xa<CR>

" different colors for normal/insert mode
au InsertEnter * hi StatusLine ctermfg=3
au InsertLeave * hi StatusLine ctermfg=7

" http://stackoverflow.com/questions/6453595/prevent-vim-from-clearing-the-clipboard-on-exit
autocmd VimLeave * call system("xsel -ib", getreg('+'))

" Editing YAML files
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" Do not show startup screen
set shm+=I
inoremap jk <Esc>

nnoremap <silent> <expr> <Leader>f (expand('%') =~ 'NERD_tree' ? "\<c-w>\<c-w>" : '').":Files\<cr>"
nmap <Leader>g :Rg<CR>
nmap <Leader>c gcc
vmap <Leader>c gc
hi Directory ctermfg=4


let g:highlightedyank_highlight_duration = 300

highlight HighlightedyankRegion ctermbg=7
