- name: Install OpenVPN client/server
  apt:
    name: openvpn
    state: present
    
- name: Put OpenVPN key
  template:
    src: "{{ playbook_dir }}/secrets/dell.key"
    dest: /etc/openvpn/dell.key
    owner: root

- name: Put OpenVPN configuration file for Dell laptop (client)
  template:
    src: ../files/openvpn-client.conf
    dest: /etc/openvpn/dell.conf
    owner: root
  when: inventory_hostname == 'dell'
  
- name: Put OpenVPN configuration file for Dell laptop (server)
  template:
    src: ../files/openvpn-server.conf
    dest: /etc/openvpn/dell.conf
    owner: root
  when: inventory_hostname == 'kelog.pl'
  
- name: Enable OpenVPN client for Dell laptop
  systemd:
    name: openvpn@dell.service
    enabled: true
    state: restarted
