- name: Install OpenVPN client/server
  apt:
    name: openvpn
    state: present
    
- name: Put OpenVPN key
  template:
    src: "{{ playbook_dir }}/secrets/dell.key"
    dest: /etc/openvpn/dell.key
    owner: root

- name: Put OpenVPN configuration files
  template:
    src: "../files/openvpn-{{ 'client' if (inventory_hostname == 'dell') else 'server' }}.conf"
    dest: /etc/openvpn/dell.conf
    owner: root

- name: Enable OpenVPN client and server
  systemd:
    name: openvpn@dell.service
    enabled: true
    state: restarted
