- name: Put systemd service for buildkit
  copy:
    src: "{{ role_path }}/files/buildkit.service"
    dest: /etc/systemd/system/buildkit.service
- name: Disable buildkit service before reinstalling
  systemd:
    name: buildkit.service
    state: stopped
    enabled: false
    daemon_reload: true
- name: Install buildkit
  shell: |
    cd /tmp
    rm -rf buildkit.tar.gz
    wget https://github.com/moby/buildkit/releases/download/v0.15.1/buildkit-v0.15.1.linux-amd64.tar.gz -O buildkit.tar.gz
    tar xf buildkit.tar.gz
    cp ./bin/* /usr/local/bin
- name: Enable buildkit service
  systemd:
    name: buildkit.service
    state: started
    enabled: true
    daemon_reload: true

- name: Clear out temporary archive download for nerdctl
  file:
    path: /tmp/nerdctl.tar.gz
    state: absent
- name: Download nerdctl
  get_url:
    url: https://github.com/containerd/nerdctl/releases/download/v1.7.6/nerdctl-1.7.6-linux-amd64.tar.gz
    dest: /tmp/nerdctl.tar.gz
- name: Unpack nerdctl
  unarchive:
    remote_src: true
    src: /tmp/nerdctl.tar.gz
    dest: /usr/local/bin/

- name: Enable IP forwarding for Kubernetes
  copy:
    src: "{{ role_path }}/files/k8s.conf"
    dest: /etc/sysctl.d/k8s.conf
- name: Force reload of sysctl parameters
  shell: sysctl --system
- name: Add required module for flannel to work
  lineinfile:
    path: /etc/modules
    line: br_netfilter
    create: yes
    state: present
- name: Force required module load now without reboot
  shell: "modprobe br_netfilter"

- name: Put systemd service for blocking external VXLAN port
  copy:
    src: "{{ role_path }}/files/k3s-block-vxlan.service"
    dest: /etc/systemd/system/k3s-block-vxlan.service
- name: Enable iptables VXLAN blocking on startup
  systemd:
    name: k3s-block-vxlan.service
    state: started
    enabled: true
    daemon_reload: true

- name: Install certbot for Lets Encrypt
  apt:
    pkg: certbot
    state: present

- name: Check if kelog.pl repository needs to be cloned
  stat:
    path: /home/kelog/kelog.pl
  register: check_kelog_pl
- name: Clone main infrastructure repository for later
  git:
    repo: 'https://github.com/AleksanderGrzybowski/kelog.pl.git'
    dest: /home/kelog/kelog.pl
    version: 'master' 
  when: not check_kelog_pl.stat.exists
    
